;; Here are some Nextstep-like bindings for command key sequences.
(keymap-global-unset "s-,")
(keymap-global-unset "s-'")
(keymap-global-unset "s-`")
(keymap-global-unset "s-~")
(keymap-global-unset "s--")
(keymap-global-unset "s-:")
(keymap-global-unset "s-?")
(keymap-global-unset "s-^")
(keymap-global-unset "s-&")
(keymap-global-unset "s-C")
(keymap-global-unset "s-D")
(keymap-global-unset "s-E")
(keymap-global-unset "s-L")
(keymap-global-unset "s-M")
(keymap-global-unset "s-S")
(keymap-global-unset "s-a")
(keymap-global-unset "s-c")
(keymap-global-unset "s-d")
(keymap-global-unset "s-e")
(keymap-global-unset "s-f")
(keymap-global-unset "s-F")
(keymap-global-unset "s-g")
(keymap-global-unset "s-h")
(keymap-global-unset "s-H")
(keymap-global-unset "M-s-h")
(keymap-global-unset "s-j")
(keymap-global-unset "s-k")
(keymap-global-unset "s-l")
(keymap-global-unset "s-m")
(keymap-global-unset "s-n")
(keymap-global-unset "s-o")
(keymap-global-unset "s-p")
(keymap-global-unset "s-q")
(keymap-global-unset "s-s")
(keymap-global-unset "s-t")
(keymap-global-unset "s-u")
(keymap-global-unset "s-v")
(keymap-global-unset "s-w")
(keymap-global-unset "s-x")
(keymap-global-unset "s-y")
(keymap-global-unset "s-z")
(keymap-global-unset "s-+")
(keymap-global-unset "s-=")
(keymap-global-unset "s--")
(keymap-global-unset "s-0")
(keymap-global-unset "s-|")
(global-unset-key [s-kp-bar])
(global-unset-key [?\C-\s- ])
(global-unset-key [s-right])
(global-unset-key [s-left])
(global-unset-key [home])
(global-unset-key [end])
(global-unset-key [kp-home])
(global-unset-key [kp-end])
(global-unset-key [kp-prior])
(global-unset-key [kp-next])
(keymap-global-unset "s-F")

(keymap-unset esc-map "s-f" 'remove)
(keymap-unset minibuffer-local-isearch-map "s-f" 'remove)
(keymap-unset isearch-mode-map "s-f" 'remove)
(keymap-unset esc-map "s-F" 'remove)
(keymap-unset minibuffer-local-isearch-map "s-F" 'remove)

(global-unset-key [S-down-mouse-1])

